### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by ghost** [speixoto/yii2-polymer#1]
Please, fill the wiki or write the guide how to use your plugin. Thanks

**Comment by speixoto** [comment]
Hi,

This is a stoped project. :( I did not had the oppirtunity to get this moving on so most of things are not working right now. :(

Date: Mon, 26 Jan 2015 13:01:07 -0800

**Comment by ghost** [comment]
Ok. Thank you. It so bad, I wanted the support of this lib to yii2 :(
